# Project: 11HASH
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = hash.o main.o
LINKOBJ  = hash.o main.o
LIBS     = -L"D:/__EXE/exe2_prof/Dev-Cpp/MinGW64/lib" -L"D:/__EXE/exe2_prof/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/__EXE/exe2_prof/Dev-Cpp/MinGW64/include" -I"D:/__EXE/exe2_prof/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/__EXE/exe2_prof/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/__EXE/exe2_prof/Dev-Cpp/MinGW64/include" -I"D:/__EXE/exe2_prof/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/__EXE/exe2_prof/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/__EXE/exe2_prof/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 11HASH.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

hash.o: hash.c
	$(CC) -c hash.c -o hash.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
